[project]
name = "customer-service-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "dotenv>=0.9.9",
    "fastapi>=0.136.1",
    "groq<1",
    "langchain>=1.2.17",
    "langchain-groq>=1.1.2",
    "langchain-text-splitters>=1.1.2",
    "mem0ai>=2.0.1",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.4.1",
    "spacy>=3.8.13",
]
